theme: jekyll-theme-cayman
title: Secure Architecture Lab.
timezone: Asia/Tokyo
url: "https://secarchlab.github.io"
baseurl: ""
github:
  is_project_page: false
show_downloads: false
google_analytics: G-BJXE573LSP
